### ISSUE TITLE
Add routing system to dummy maps using dummy data for now.

### ISSUE THREAD

**Issue by Trisanu-007** [VikrantReddy/Traffic-management-and-simulation#4] opened 2020-10-24 15:11 UTC
Use and make a routing data using dummy traffic densities for now

**Comment by Trisanu-007** [comment] 2020-10-24 15:56
Please review @VikrantReddy @Nikhil-Vaddipati

**Comment by VikrantReddy** [comment] 2020-10-25 10:22
@Trisanu-007 Could you please name the nodes for easier usage?

**Comment by VikrantReddy** [comment] 2020-10-25 10:32
Duplicate of #3

**Closed as completed** 2020-10-25 10:33 UTC
Labels: duplicate, core
